import type { TrackerDef } from '../../../trackers/types';

export const herbs: TrackerDef = {
  id: 'rdr2:herbs',
  game: 'rdr2',
  title: 'Herbs',
  subtitle: 'Every gatherable herb in the base game',
  items: [
    // Berries
    { id: 'blackberry', name: 'Blackberry', category: 'Berries', location: 'West Elizabeth, Lemoyne — forests and riverbanks' },
    { id: 'evergreen-huckleberry', name: 'Evergreen Huckleberry', category: 'Berries', location: 'Ambarino, New Hanover — coniferous forests' },
    { id: 'red-raspberry', name: 'Red Raspberry', category: 'Berries', location: 'New Hanover, West Elizabeth — woodland edges' },
    { id: 'wintergreen-berry', name: 'Wintergreen Berry', category: 'Berries', location: 'Roanoke Ridge, Grizzlies — northern forests' },
    // Mushrooms
    { id: 'bay-bolete', name: 'Bay Bolete', category: 'Mushrooms', location: 'West Elizabeth, New Hanover — forest floors' },
    { id: 'chanterelles', name: 'Chanterelles', category: 'Mushrooms', location: 'Roanoke Ridge, West Elizabeth — damp forest floors' },
    { id: 'parasol-mushroom', name: 'Parasol Mushroom', category: 'Mushrooms', location: 'West Elizabeth, Lemoyne — grasslands and forest edges' },
    { id: 'rams-head', name: "Ram's Head", category: 'Mushrooms', location: 'Grizzlies East and West — high alpine areas' },
    // Flowers
    { id: 'acunas-star-orchid', name: "Acuna's Star Orchid", category: 'Flowers', location: 'Bayou Nwa, Lemoyne — swampland' },
    { id: 'cigar-orchid', name: 'Cigar Orchid', category: 'Flowers', location: 'Bayou Nwa, Lemoyne — swamps and bayou edges' },
    { id: 'clamshell-orchid', name: 'Clamshell Orchid', category: 'Flowers', location: 'Bluewater Marsh, Lemoyne — wetlands' },
    { id: 'creeping-thyme', name: 'Creeping Thyme', category: 'Flowers', location: 'West Elizabeth, Lemoyne — open meadows' },
    { id: 'desert-sage', name: 'Desert Sage', category: 'Flowers', location: 'New Austin — Cholla Springs and Río Bravo' },
    { id: 'dragons-mouth-orchid', name: "Dragon's Mouth Orchid", category: 'Flowers', location: 'Grizzlies, Ambarino — high mountain meadows' },
    { id: 'english-mace', name: 'English Mace', category: 'Flowers', location: 'New Hanover, Lemoyne — grasslands and roadsides' },
    { id: 'ghost-orchid', name: 'Ghost Orchid', category: 'Flowers', location: 'Bayou Nwa, Lemoyne — deep swamp' },
    { id: 'hummingbird-sage', name: 'Hummingbird Sage', category: 'Flowers', location: 'West Elizabeth, Lemoyne — forested hillsides' },
    { id: 'lady-of-the-night-orchid', name: 'Lady of the Night Orchid', category: 'Flowers', location: 'Bayou Nwa, Lemoyne — swamps and wetlands' },
    { id: 'lady-slipper-orchid', name: 'Lady Slipper Orchid', category: 'Flowers', location: 'Roanoke Ridge — forested areas near waterways' },
    { id: 'milkweed', name: 'Milkweed', category: 'Flowers', location: 'New Hanover, West Elizabeth — open fields and roadsides' },
    { id: 'moccasin-orchid', name: 'Moccasin Orchid', category: 'Flowers', location: 'Lemoyne — Bluewater Marsh and Bayou Nwa' },
    { id: 'night-scented-orchid', name: 'Night Scented Orchid', category: 'Flowers', location: 'Bluewater Marsh, Lemoyne — wetland marshes' },
    { id: 'oleander-sage', name: 'Oleander Sage', category: 'Flowers', location: 'Lemoyne — Bluewater Marsh and Bayou Nwa' },
    { id: 'oregano', name: 'Oregano', category: 'Flowers', location: 'Lemoyne, New Austin — dry open areas' },
    { id: 'prairie-poppy', name: 'Prairie Poppy', category: 'Flowers', location: 'New Hanover, West Elizabeth — open grasslands' },
    { id: 'queens-orchid', name: "Queen's Orchid", category: 'Flowers', location: 'Bayou Nwa, Lemoyne — swamps' },
    { id: 'rat-tail-orchid', name: 'Rat Tail Orchid', category: 'Flowers', location: 'Lemoyne — Bluewater Marsh and Bayou Nwa' },
    { id: 'red-sage', name: 'Red Sage', category: 'Flowers', location: "New Austin — Cholla Springs and Hennigan's Stead" },
    { id: 'sparrow-egg-orchid', name: 'Sparrow Egg Orchid', category: 'Flowers', location: 'Roanoke Ridge — forested hillsides' },
    { id: 'spider-orchid', name: 'Spider Orchid', category: 'Flowers', location: 'West Elizabeth — Big Valley and Tall Trees' },
    { id: 'vanilla-flower', name: 'Vanilla Flower', category: 'Flowers', location: 'Lemoyne — Bayou Nwa and Scarlett Meadows' },
    { id: 'violet-snowdrop', name: 'Violet Snowdrop', category: 'Flowers', location: 'Grizzlies West, Ambarino — high altitude snowfields' },
    { id: 'wild-feverfew', name: 'Wild Feverfew', category: 'Flowers', location: 'New Hanover, Lemoyne — grasslands and meadows' },
    { id: 'wild-mint', name: 'Wild Mint', category: 'Flowers', location: 'New Hanover, West Elizabeth — streamsides and meadows' },
    // Other
    { id: 'alaskan-ginseng', name: 'Alaskan Ginseng', category: 'Other', location: 'Ambarino, Grizzlies — mountain slopes and forests' },
    { id: 'american-ginseng', name: 'American Ginseng', category: 'Other', location: 'New Hanover, West Elizabeth — forested areas' },
    { id: 'blackcurrant', name: 'Blackcurrant', category: 'Other', location: 'New Austin — Cholla Springs, Río Bravo, Gaptooth Ridge' },
    { id: 'burdock-root', name: 'Burdock Root', category: 'Other', location: 'New Hanover, Lemoyne — roadsides and disturbed ground' },
    { id: 'common-bulrush', name: 'Common Bulrush', category: 'Other', location: 'Lemoyne, New Hanover — swamps and riverbanks' },
    { id: 'golden-currant', name: 'Golden Currant', category: 'Other', location: 'New Hanover, West Elizabeth — riverbanks and thickets' },
    { id: 'indian-tobacco', name: 'Indian Tobacco', category: 'Other', location: 'New Hanover, Lemoyne — open fields and roadsides' },
    { id: 'wild-carrot', name: 'Wild Carrot', category: 'Other', location: 'New Hanover, West Elizabeth — open fields and meadows' },
    { id: 'yarrow', name: 'Yarrow', category: 'Other', location: 'New Hanover, Lemoyne — Heartlands and Dewberry Creek' },
  ],
};
